apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
    release: kind-prometheus   # must match your Prometheus release
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http               # <-- important
      protocol: TCP
      port: 5000
      targetPort: 5000
