apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-servicemonitor
  namespace: monitoring
  labels:
    release: kind-prometheus   # must match your Prometheus Helm release
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http              # must match Service port name
      path: /metrics         # Node.js metrics endpoint
      interval: 15s
  namespaceSelector:
    matchNames:
      - default               # namespace of your backend
